doctrine:
    dbal:
        dbname:               emeu17
        host:                 blu-ray.student.bth.se
        port:                 3306
        user:                 emeu17
        password:             '%env(DATABASE_PASSWORD)%'
        driver:               pdo_mysql
        # url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Emeu17:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Emeu17\Entity'
                alias: Emeu17
